server:
  port: 8080

spring:
  application:
    name: tour-mission-service

  datasource:
    url: jdbc:mysql://${DB_HOST}:${DB_PORT}/${DB_NAME}?useSSL=false&serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: false
        dialect: ${SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT}
    defer-datasource-initialization: true
  
  sql:
    init:
      mode: never

jwt:
  secret: ${JWT_SECRET}
  access-expiration: 21599999
  refresh-expiration: 5183999999

cloud:
  aws:
    s3:
      bucket: ${AWS_S3_BUCKET}
    credentials:
      access-key: ${AWS_ACCESS_KEY}
      secret-key: ${AWS_SECRET_KEY}
    region:
      static: ${AWS_REGION}

kakao:
  client-id: ${KAKAO_CLIENT_ID}
  client-secret: ${KAKAO_CLIENT_SECRET}
  redirect-uri: ${KAKAO_REDIRECT_URI}
  kauth-host: https://kauth.kakao.com
  kapi-host: https://kapi.kakao.com
  route-api-key: ${KAKAO_ROUTE_API_KEY}

cors:
  allowed-origins: ${CORS_ALLOWED_ORIGINS}

springdoc:
  swagger-ui:
    path: /api-test
    groups-order: DESC
    tags-sorter: alpha
    operations-sorter: method
  paths-to-match: /api/**